export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

// SESSION
export const SET_SESSION = 'SET_SESSION'
export const PURGE_SESSION = 'PURGE_SESSION'

// CHARACTERS
// export const ADD_CHARACTER = 'ADD_CHARACTER'
export const INIT_LISTS = 'INIT_LISTS'
// export const SET_DETAILS = 'SET_DETAILS'

// NAV
export const SET_NAV = 'SET_NAV'
