
// SESSION
export const SET_SESSION = 'SET_SESSION'
export const PURGE_SESSION = 'PURGE_SESSION'

// CHARACTERLISTS
export const SYNC_CHAR_LISTS = 'SYNC_CHAR_LISTS'

// CHARACTERS
export const SET_CHARACTER = 'SET_CHARACTER'

// QUESTLOGS
export const SET_QUEST_LOG = 'SET_QUEST_LOG'

// KINDERS
export const SET_KINDERS = 'SET_KINDERS'

// LEVELINGS
export const SET_LEVELING = 'SET_LEVELING'

// NAV
export const SET_NAV = 'SET_NAV'
